### ISSUE TITLE
Differentiate Enemy from Player

### ISSUE THREAD

**Issue by manav95** [DesViv/AIGAME#11]
We want to be able to differentiate the enemy from the player. The player needs to be able to attack and the enemy needs to be hooked up to AI.

**Comment by jcole123** [comment]
You can already differentiate using a GameObject's tag. "Player" = player 1, "Player2" = player2. We could also use the Enemy class to setup AI, since I think there's already a function in there that moves the units around. Attacking already works as well (for the player).

**Comment by jcole123** [comment]
Also you might have noticed already but the code in your branch is outdated. Player/GameManager especially.

**Comment by manav95** [comment]
really how so?

**Comment by tallen12** [comment]
What branch is the most current one?

**Comment by manav95** [comment]
master. Disregard newbranch
