### ISSUE TITLE
Game Manager Players object does not exist

### ISSUE THREAD

**Issue by tallen12** [DesViv/AIGAME#12]
The name players does not exist in this context.

It doesn't let me run or compile code. 
This may be something @manav95  has done in trying to make something work. Can you take a look and see why this changed?

**Comment by jcole123** [comment]
I'll look at it asap. Unity decided to start crashing again every time I start it so I have to get it running first.

**Comment by jcole123** [comment]
There use to be a single list of players like 5 commits ago, I'm pretty sure he was looking at old code when he wrote update() in GameManager.
