### ISSUE TITLE
Player steps don't reset after used

### ISSUE THREAD

**Issue by tallen12** [DesViv/AIGAME#23]
The player steps don't reset after being used.

**Comment by jcole123** [comment]
I'll take a look

**Comment by jcole123** [comment]
I can't even see the console right now unity keeps starting the game in full screen when I press play. Has to be an error with endTurn() GameManager though

**Comment by tallen12** [comment]
There is a start on maximize in the top right corner. That is why it is maximizing.

**Comment by jcole123** [comment]
Yeah, but I can't see the button because it's rendering the game on top of the editor for some reason. I'll click around blindly until I fix it.

**Comment by jcole123** [comment]
Should be working now.
